#  ------------------------------------------------------------------------------------------
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
#  ------------------------------------------------------------------------------------------
import logging
import math
import os
from collections import OrderedDict
import argparse
import time

import torch
from torch import nn
from torch.nn import CrossEntropyLoss, MSELoss
import torch.nn.functional as F
from torch.optim import Optimizer
from torch.optim.lr_scheduler import LambdaLR, _LRScheduler

from galore_projector import GaLoreProjector
from galore_projector_tensor import GaLoreProjectorTensor


def save_galore_subspace_if_needed(param_name, p, state, group):
    """
    Save the GaLore projection matrix for selected layers.

    This function saves only the projection matrix generated by GaLore,
    not the full gradient tensor.
    """
    rank_id = int(os.environ.get("RANK", "0"))
    if rank_id != 0:
        return

    target_keywords = [
        "h.2.attn.c_attn.weight",
        "h.2.mlp.c_fc.weight",
        "h.12.attn.c_attn.weight",
        "h.12.mlp.c_fc.weight",
        "h.22.attn.c_attn.weight",
        "h.22.mlp.c_fc.weight",
    ]

    if not any(key in param_name for key in target_keywords):
        return

    if state["step"] % group["update_proj_gap"] != 0:
        return

    if "projector" not in state:
        return

    projector = state["projector"]

    if not hasattr(projector, "ortho_matrix"):
        return

    if projector.ortho_matrix is None:
        return

    save_dir = os.path.abspath(
        os.path.join(
            "./subspace",
            f"rank_{group['galore_rank']}_gap_{group['update_proj_gap']}"
        )
    )
    os.makedirs(save_dir, exist_ok=True)

    safe_name = param_name.replace(".", "_")
    save_path = os.path.join(save_dir, f"{safe_name}_step_{state['step']}.pt")

    torch.save(
        {
            "step": state["step"],
            "param_name": param_name,
            "grad_shape": tuple(p.grad.shape),
            "ortho_matrix": projector.ortho_matrix.detach().cpu(),
        },
        save_path
    )

    print(f"[Saved GaLore subspace] {save_path}")


def add_optimizer_params(parser: argparse.ArgumentParser):
    parser.add_argument('--lr', default=0.00001, type=float, help='learning rate')
    parser.add_argument('--weight_decay', default=0.01, type=float, help='weight decay rate')
    parser.add_argument('--correct_bias', action='store_true', help='correct adam bias term')
    parser.add_argument('--adam_epislon', default=1e-6, type=float, help='adam epsilon')
    parser.add_argument('--no_decay_bias', action='store_true', help='no weight decay on bias weigh')
    parser.add_argument('--adam_beta1', default=0.9, type=float, help='adam beta1 term')
    parser.add_argument('--adam_beta2', default=0.98, type=float, help='adam beta2 term')

    parser.add_argument(
        '--scheduler',
        default='linear',
        type=str,
        choices=['cosine', 'inv_sqrt', 'dev_perf', 'constant', 'linear', 'cycle', 'None'],
        help='lr scheduler to use.'
    )

    parser.add_argument('--max_step', type=int, default=None, help='upper epoch limit')
    parser.add_argument('--max_epoch', type=int, default=None, help='max epoch of training')
    parser.add_argument('--warmup_step', type=int, default=0, help='upper epoch limit')
    parser.add_argument('--i_steps', type=str, default='0', help='interval_steps')
    parser.add_argument('--i_lrs', type=str, default='0.00025', help='interval_lrs')

    # GaLore parameters
    parser.add_argument("--galore_rank", type=int, default=128)
    parser.add_argument("--update_proj_gap", type=int, default=50)
    parser.add_argument("--galore_scale", type=float, default=1.0)
    parser.add_argument("--proj_type", type=str, default="std")


class AdamW_galore(Optimizer):
    """
    Implements AdamW with optional GaLore gradient projection.
    """

    def __init__(
        self,
        params,
        lr=1e-3,
        betas=(0.9, 0.98),
        eps=1e-6,
        weight_decay=0.0,
        correct_bias=True,
        galore_rank=4,
        update_proj_gap=200,
        scale=1.0,
        proj_type='std'
    ):
        if lr < 0.0:
            raise ValueError(f"Invalid learning rate: {lr} - should be >= 0.0")
        if not 0.0 <= betas[0] < 1.0:
            raise ValueError(f"Invalid beta parameter: {betas[0]} - should be in [0.0, 1.0)")
        if not 0.0 <= betas[1] < 1.0:
            raise ValueError(f"Invalid beta parameter: {betas[1]} - should be in [0.0, 1.0)")
        if not 0.0 <= eps:
            raise ValueError(f"Invalid epsilon value: {eps} - should be >= 0.0")

        defaults = dict(
            lr=lr,
            betas=betas,
            eps=eps,
            weight_decay=weight_decay,
            correct_bias=correct_bias,
            galore_rank=galore_rank,
            update_proj_gap=update_proj_gap,
            scale=scale,
            proj_type=proj_type
        )
        super().__init__(params, defaults)

    def reset_state(self):
        for group in self.param_groups:
            for p in group['params']:
                state = self.state[p]
                state['step'] = 0
                state["exp_avg"] = torch.zeros_like(p.data)
                state["exp_avg_sq"] = torch.zeros_like(p.data)

    @torch.no_grad()
    def step(self, closure=None):
        """
        Performs a single optimization step.
        """
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p in group["params"]:
                if p.grad is None:
                    continue

                grad = p.grad

                if grad.is_sparse:
                    raise RuntimeError("Adam does not support sparse gradients, please consider SparseAdam instead")

                state = self.state[p]

                if "step" not in state:
                    state["step"] = 0

                if "dim" not in group:
                    group["dim"] = 2


                # GaLore projection
                if "galore_rank" in group:
                    if "projector" not in state:
                        if group["dim"] <= 2:
                            state["projector"] = GaLoreProjector(
                                group["galore_rank"],
                                update_proj_gap=group["update_proj_gap"],
                                scale=group["scale"],
                                proj_type=group["proj_type"]
                            )
                        else:
                            state["projector"] = GaLoreProjectorTensor(
                                group["galore_rank"],
                                update_proj_gap=group["update_proj_gap"],
                                scale=group["scale"],
                                proj_type=group["proj_type"]
                            )

                    if grad.dim() >= 2:
                        start = time.perf_counter()

                        grad = state["projector"].project(grad, state["step"])


                        # param_name = getattr(self, "param_name_map", {}).get(id(p), "unknown")
                        #
                        # print(
                        #     f"[DEBUG] call save func: param={param_name}, step={state['step']}, grad_shape={tuple(grad.shape)}")
                        #
                        # save_galore_subspace_if_needed(
                        #     param_name=param_name,
                        #     p=p,
                        #     state=state,
                        #     group=group
                        # )
                        #
                        # end = time.perf_counter()
                        #
                        # if param_name != "unknown" and any(
                        #     key in param_name for key in [
                        #         "h.2.attn.c_attn.weight",
                        #         "h.2.mlp.c_fc.weight",
                        #         "h.12.attn.c_attn.weight",
                        #         "h.12.mlp.c_fc.weight",
                        #         "h.22.attn.c_attn.weight",
                        #         "h.22.mlp.c_fc.weight",
                        #     ]
                        # ):
                        #     print(
                        #         f"[GaLore projector] param={param_name}, "
                        #         f"step={state['step']}, "
                        #         f"time={(end - start) * 1000:.2f} ms"
                        #     )

                # State initialization
                if "exp_avg" not in state:
                    state["exp_avg"] = torch.zeros_like(grad)
                    state["exp_avg_sq"] = torch.zeros_like(grad)

                exp_avg, exp_avg_sq = state["exp_avg"], state["exp_avg_sq"]
                beta1, beta2 = group["betas"]

                state["step"] += 1

                exp_avg.mul_(beta1).add_(grad, alpha=(1.0 - beta1))
                exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1.0 - beta2)

                denom = exp_avg_sq.sqrt().add_(group["eps"])

                step_size = group["lr"]
                if group["correct_bias"]:
                    bias_correction1 = 1.0 - beta1 ** state["step"]
                    bias_correction2 = 1.0 - beta2 ** state["step"]
                    step_size = step_size * math.sqrt(bias_correction2) / bias_correction1

                norm_grad = exp_avg / denom

                # GaLore projection back
                if "galore_rank" in group:
                    if grad.dim() >= 2:
                        norm_grad = state["projector"].project_back(norm_grad)

                p.add_(norm_grad, alpha=-step_size)

                if group["weight_decay"] > 0.0:
                    p.add_(p, alpha=(-group["lr"] * group["weight_decay"]))

        return loss
